% School of Civil Engineering, Central South University
% H.P.Duan, hpduan2000@csu.edu.cn
% https://www.hpduan.cn
function axStandard()
set(gca, 'Box', 'off', ...
    'Layer','top',...
    'LineWidth',1.2,...
    'XGrid', 'off', 'YGrid', 'off', ...
    'TickDir', 'out', 'TickLength', [0.02 0.02], ...
    'XMinorTick', 'off', 'YMinorTick', 'off', ...
    'XColor', [.1 .1 .1],  'YColor', [.1 .1 .1])
set(gca, 'FontName', 'Arial', 'FontSize', 20)
set(gca,'looseInset',[0 0 0 0])
set(gcf,'Color',[1 1 1])
xc = get(gca,'XColor');
yc = get(gca,'YColor');
unit = get(gca,'units');
ax = axes( 'Units', unit,...           
    'Position',get(gca,'Position'),...           
    'XAxisLocation','top',...           
    'YAxisLocation','right',...           
    'Color','none',...           
    'XColor',xc,...           
    'YColor',yc);
set(ax, 'linewidth',1.2,...        
    'XTick', [],...        
    'YTick', []);
end

